### ISSUE TITLE
Linux FLM beta issue

### ISSUE THREAD

**Issue by bluefalcon13** [lemonade-sdk/lemonade#1296]
Currently, lemonade-server uses `which flm` to detect your flm binary location. I will have a PR shortly for updating the docs.

Would it be better overall to follow the precedent set by custom llama-ccp and sd-cpp binaries to use an environment variable to set the path?

Maybe a little bit of a edge-case, but especially as an archlinux docker user, it just bit me for a while of my time trying to figure out what I was doing wrong! :P

**Comment by OmerFarukOruc** [comment]
I managed to get the Linux FLM beta working on Fedora 43 with an XDNA2 laptop, so here are some concrete notes that may help both docs and runtime detection.

### Tested hardware / distro

- ASUS ROG Zephyrus G16
- AMD Ryzen AI 9 HX 370 (`17f0:10`, XDNA2 / Strix)
- Fedora 43
- Kernel: `6.19.3-cachyos3.fc43.x86_64`

### Working end state

After setup and reboot:

- `ulimit -l` => `unlimited`
- `flm validate` succeeds
- Lemonade service is running and detects FLM on Linux
- `GET /api/v1/models` returns `200 OK`

### What actually worked on Fedora

I did **not** get there via distro packages alone.

The path that worked was:

1. Build and package XRT from `amd/xdna-driver` (`xrt-base`, `xrt-base-devel`, `xrt-npu`)
2. Build and package `xrt_plugin-amdxdna`
3. Install those local RPMs
4. Build FastFlowLM from source and install it under `/opt/fastflowlm`
5. Install `lemonade-server` from the `abn/lemonade` COPR

### Friction points I hit

#### 1. `which flm` detection is too brittle on Linux

I had to replace `/usr/local/bin/flm` with a wrapper script instead of a plain symlink, because FLM also needed:

- `LD_LIBRARY_PATH=/opt/fastflowlm/lib:/opt/xilinx/xrt/lib`
- `FLM_CONFIG_PATH=/opt/fastflowlm/share/flm/model_list.json`

Without that, plain `flm` or Lemonade's FLM probe could fail even though the binary itself existed.

So yes: I think an environment-variable override would be better than relying only on `which flm`.

Something like:

- `LEMONADE_FLM_PATH`
- `LEMONADE_FLM_CONFIG_PATH`

would be very helpful.

#### 2. Lemonade service also needed explicit runtime env on Linux

I had to add a systemd drop-in for `lemonade-server.service`:

```ini
[Service]
Environment=LEMONADE_FLM_LINUX_BETA=1
Environment=LD_LIBRARY_PATH=/opt/fastflowlm/lib:/opt/xilinx/xrt/lib
Environment=FLM_CONFIG_PATH=/opt/fastflowlm/share/flm/model_list.json
LimitMEMLOCK=infinity
```

Before that, the service started, but the backend probe failed with:

```text
flm: error while loading shared libraries: libxrt_coreutil.so.2: cannot open shared object file: No such file or directory
```

#### 3. Memlock failure mode was misleading

After writing `/etc/security/limits.d/99-amdxdna.conf`, the **existing shell** still kept the old hard limit until reboot / fresh login.

That produced confusing errors like:

```text
[xrt-smi] ERROR: mmap(..., len=67108864, ...) failed (err=-11): Resource temporarily unavailable
```

and `flm validate` complaining about low memlock.

So for docs, I would call out very explicitly:

- editing `limits.d` is not retroactive for the current shell
- users need a full re-login or reboot

#### 4. Linux firmware versioning looked surprising

The old-style Linux notes/examples mention firmware versions like `1.1.x.x`, but the working Strix firmware from AMD's current `xdna-driver` package reported:

```text
255.0.11.69
```

That came from both:

- `/sys/bus/pci/drivers/amdxdna/*/fw_version`
- `xdna-driver/tools/info.json` for `17f0_10`

So Linux users may need a note saying that the live firmware version format may differ from earlier examples.

#### 5. `lemonade-server recipes` is confusing in Linux FLM beta context

On my system, FLM was actually working, but `lemonade-server recipes` still reported:

```text
flm  npu  unsupported  Requires Windows
```

That made it look like Linux FLM beta was impossible, even though `flm validate` and Lemonade's own backend scan were good.

I think that status line probably needs a beta-aware override or at least a clearer message.

### Fedora-specific note

The `lemonade-app` COPR package did not install cleanly for me on Fedora because it wanted an `electron` dependency that was not available from the repos I tested.

I worked around that by using the official AppImage instead.

### Suggestion

If you want, I can turn this into a cleaner Fedora 43 setup doc / checklist. At minimum I think the docs should mention:

- working FLM binary path override / env var
- `LD_LIBRARY_PATH` and `FLM_CONFIG_PATH` requirements
- memlock + reboot requirement
- Linux beta recipe/status mismatch
- Fedora/COPR GUI caveat

**Comment by OmerFarukOruc** [comment]
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/dceec09a-ec5d-478b-8120-6bc46ae6935e" />

**Comment by jeremyfowers** [comment]
@superm1 thoughts here? Especially on the `which` problems, which seem to be affecting a fair amount of people.

**Comment by bluefalcon13** [comment]
> LD_LIBRARY_PATH=/opt/fastflowlm/lib:/opt/xilinx/xrt/lib

I'm a huge fan of letting Linux do the work and getting out of its way. When I have issues like this, I almost always do something like this:

```bash
echo "/opt/fastflowlm/lib" > /etc/ld.so.conf.d/flm.conf
echo "/opt/xilinx/xrt/lib" > /etc/ld.so.conf.d/xrt.conf
ldconfig
```

That would likely solve the issue with launching via script on your side (and be robust in the case of flm/xrt things).

**Comment by superm1** [comment]
> I'm a huge fan of letting Linux do the work and getting out of its way. When I have issues like this, I almost always do something like this:

It's a balancing act which paths to include.  A system's default `LD_LIBRARY_PATH` does _not_ search anything in `/opt`, and I don't feel it's a good idea to start precedent in doing this.

XRT when built for Ubuntu, Debian, and Arch puts things in `/usr/lib` (which is part of the default search path).  XRT when built from source can be configured to put it in `/opt`, or `/usr/local`, or anything a user wants really.

So considering this - I think it's not Lemonade's responsibility to discover how your system is set up.  I tend to agree, the default search path should be configured by the system's link paths.  If you put something in `/usr/local` or `/opt/` and those aren't in the search path, _you_ should be responsible for adding them.

So TL;DR I agree with you.  Document what people should do.  Maybe we should have a "generic" target for FLM instructions for people without distro packages.

> 5. lemonade-server recipes is confusing in Linux FLM beta context

We have a breaking change where `flm` uses `ready` in the json instead of `ok` and the matching change is only on the npu-json branch.

> 4. Linux firmware versioning looked surprising

You're running a development version of firmware, not a production version.  You are running at main branch of xdna presumably, not the 2.21.* like all the other distros.

---

I'm not going to touch on everything else, but I will say there is a lot of things that happen automatically because of how things are packaged in Debian/Ubuntu/Arch which make it a **lot** easier.    I fought with a lot of these areas that you point out.

I feel our right direction for Fedora is we need to get XRT, XRT XDNA Plugin, and FLM packaged into proper RPMs that follow FHS.  Nearly everything you've pointed out becomes a non-starter then.

**Comment by X-Ryl669** [comment]
Just a remark here, 2.21 doesn't build with 6.19.8 kernel (due to removal of DRM_ERROR/DRM_INFO macros used in xrt 2.21 but no more in the kernel). Since 7.0 isn't GA yet, no solution with official package work without building xrt and amdxdna without version 2.23 at least on the current latest and official kernel.

So the official xrt package just leads to a broken system on rolling release systems like Arch and its children. It works on Debian and Fedora system because they are using an outdated kernel (or a non released kernel). 

Since fastflowlm requires xrt, you're out of luck with "official" packages. And as soon as you build from source, you'll end up with xrt installed in `/opt/xilinx`. It's not our choice, it's AMD's choice to install there, look into amd-xdna repository for the Arch PKGBUILD script, it's `/opt` right there.

Anyway, on my Arch system, lemonade doesn't detect flm as an available backend, despite flm validating correctly (and working on CLI). So, no, even on Arch it doesn't work like you are claiming it does. `amd-xdna/dkms` from AUR doesn't work out of the box too (I've never succeeded detecting my NPU with this module, even with official xrt package (2.21) installed)

So the only working configuration on Arch is to install fastflowlm, then `pacman -Rdd xrt` to remove that pesky outdated dependency that fails DKMS building and clone amd-xdna driver repository and build the xrt & module package from here to install those. It's not something that's in the documentation and not easy to come from. Also, if lemonade runs once with xrt **not set up correctly**, it'll write an undocumented `~/.cache/lemonade/hardware_info.json` file containing the NPU missing information. Even when you'll get a working xrt setup, **until you delete that file**, lemonade will refuse to install flm backend. This is clearly a bug, IMHO, since when you ask to install a backend, you should not rely on whatever state the system was 2 weeks ago. On an eGPU system, you'll get the same issue too.

The idiosyncrasy of the LD_PRELOAD hack of xrt is also very unfriendly. Imagine the hell it'd be if all software on your computer had to add their path to the LD_PRELOAD environment, yet, that's how AMD/Xilinx is packaging their software and expecting them to work. 

Arch linux will not install a rc kernel for its `linux` package. Currently it's at [6.19.8](https://archlinux.org/packages/core/x86_64/linux/) and not 7.0rc2, so the instruction in the Arch's guide on lemonade website are wrong and were not even tested. 

IMHO, detecting fastflowlm should happen **after** checking a configuration file telling how to find and run the binary. That way, any distribution will be able to use this software, not only those that have a "pseudo debian/fedora like" system.

**Comment by superm1** [comment]
Multiple comments:
 
2. Arch moved to `/usr` just like Debian a few weeks ago: https://gitlab.archlinux.org/archlinux/packaging/packages/xrt/-/commit/3ff167dead02de0a5f22780dd2be12cb19c6d357
3. The kernel build problem you saw is for Alveo support which isn't needed.  This turns it off.  https://gitlab.archlinux.org/archlinux/packaging/packages/xrt/-/merge_requests/5
4. Completely agree we shouldn't be having hardware cache.  This drops it:  https://github.com/lemonade-sdk/lemonade/pull/1354

**Comment by superm1** [comment]
Also; in case you didn't know fastflowlm is packaged now for arch too: https://gitlab.archlinux.org/archlinux/packaging/packages/fastflowlm

**Comment by superm1** [comment]
Also if you want the DKMS package; here is an AUR of just that.
https://aur.archlinux.org/packages/amdxdna-dkms

**Comment by X-Ryl669** [comment]
The xrt package in Arch official doesn't build because of changes in 6.19, not because of the configuration.
```
xocl_drv.c:1419:3: error: call to undeclared function 'DRM_ERROR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1419 |                 DRM_ERROR("Request %lld, round down to power of 2 %lld\n",
      |                 ^
xocl_drv.c:1441:5: error: call to undeclared function 'DRM_ERROR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1441 |                                 DRM_ERROR("duplicated Huge Page");
      |                                 ^
xocl_drv.c:1449:4: error: call to undeclared function 'DRM_ERROR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1449 |                         DRM_ERROR("Invalid Huge Page");
      |                         ^
xocl_drv.c:1477:4: error: call to undeclared function 'DRM_ERROR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1477 |                         DRM_ERROR("CMA memory mixmatch");
      |                         ^
xocl_drv.c:1538:3: error: call to undeclared function 'DRM_ERROR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1538 |                 DRM_ERROR("Unable to alloc numa pages, %d", order);
      |                 ^
xocl_drv.c:1594:3: error: call to undeclared function 'DRM_ERROR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1594 |                 DRM_ERROR("Invalid CMA bank size");
      |                 ^
xocl_drv.c:1599:3: error: call to undeclared function 'DRM_WARN'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1599 |                 DRM_WARN("Unable to allocate with page size 0x%llx", page_sz);
      |                 ^
xocl_drv.c:1630:4: error: call to undeclared function 'DRM_ERROR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1630 |                         DRM_ERROR("CMA memory mixmatch");
      |                         ^
xocl_drv.c:1672:4: error: call to undeclared function 'DRM_INFO'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1672 |                         DRM_INFO("HOST MEM already allocated, skip");
      |                         ^
xocl_drv.c:1675:4: error: call to undeclared function 'DRM_ERROR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1675 |                         DRM_ERROR("HOST MEM already allocated, size 0x%llx", allocated_size);
      |                         ^
xocl_drv.c:1702:2: error: call to undeclared function 'DRM_INFO'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1702 |         DRM_INFO("%s, %d", __func__, err);
      |         ^
11 errors generated.
```
It builds fine with 6.18 so it's clearly a outdated source code issue. I don't think there's a point in maintaining XRT 2.21 anyway, since XRT 2.23 works perfectly for both version and likely will for 7.0 when it's out.
It's also a PITA to use since it's delivering outdated DKMS conf script (with a CLEAN rule that's deprecated since 2 years!) and a MAKE rule ending with `; cd ../..` which breaks on Clang build kernels (like mine). DKMS make rule isn't a shell script, it's a variable and it shouldn't be used like a script. So I have to manually fix a DKMS config file on my system everytime the xrt module is updated.
 
I've submitted a PR in last December for fixing this and it was merged in xrt repository, it's included in 2.23, yet the version in Arch is using a broken version that's 3 month late. This isn't the idea I have for a rolling release OS.

Anyway, I've manually patched 2.21 to build (by simply commenting those macro/functions call) and also tried to use amd-xdna/dkms. But the combination did not work (xrt-smi couldn't detect my NPU, dmesg complained with hardware init issues).
Since solving this implied digging into the source code of an outdated software, I gave up and installed from (latest) source.

I'd love not having to use a manually packaged build, but clearly, it's not working here and I doubt it'll be better in the future until xrt is fast forwarded to 2.23 version in Arch at least. I don't mind using a external amdxdna module for now, since I know I'll be able to drop it once 7.0 is out.

Again, the instruction on the website are wrong (the current kernel in Arch doesn't build xrt package, and amdxdna/dkms doesn't work), you're on your own if you need to install FLM, XRT, amdxdna. All of that would be solved by bumping the XRT version in the package IMHO.

**Comment by sofiageo** [comment]
@X-Ryl669 the instructions both on the lemonade website and on https://wiki.archlinux.org/title/Lemonade work fine. Me and many other users on Arch Linux and CachyOS have tested them. Why are you trying to build xrt? It is already built by the Arch Linux repositories. 

If there are improvements that can be made to the (temporary) `amdxdna-dkms` package feel free to comment on the package AUR page, I will take a look. But there shouldn't be an issue in using Lemonade with FLM support in Arch or Arch based distributions at the moment.

**Comment by X-Ryl669** [comment]
I'm highly skeptical about your claims here. I'm using CachyOS as well and CachyOS builds its kernel with clang/LLVM. 

This means that one *must* append `LLVM=1` to the module & kernel make invocation, else it fails. Since the xrt package in Arch linux does have the wrong dkms.conf file for both xrt and xrt-aws, containing:
```
MAKE[0]="cd driver/xocl; make KERNEL_SRC=${kernel_source_dir}; cd ../.."
CLEAN="cd driver/xocl; make clean KERNEL_SRC=${kernel_source_dir}; cd ../.."
```
It can't build on CachyOS's kernel, since DKMS will try to run `cd driver/xocl; make KERNEL_SRC=${kernel_source_dir}; cd ../.. LLVM=1` instead of `make KERNEL_SRC=${kernel_source_dir} LLVM=1` as it should. 

So no, it **doesn't work** with CachyOS, unless you install an Arch kernel (that's not built with clang). But doing so actually breaks all other modules you might have on your system that depends on the CachyOS's specific changes of the kernel (like all modules that'll build with LLVM/Clang). You're creating a chimera OS, which is **a terrific idea**. It might work for you, until CachyOS updates its kernel and everything will collapse and you'll have to fix DKMS's issues (ask me how I know).

And if you have a Arch linux system, the instructions don't work either (I've tried them too) since Arch linux current kernel is 6.19.8 and xrt 2.21 doesn't support this kernel (see my previous message for the DKMS building errors of xrt, I've copied and pasted them above). There was a fix pushed to XRT by @superm1 [2 days ago](https://github.com/Xilinx/XRT/pull/9672) so it's clearly not working with the current version of xrt in Arch.

@superm1: I've double checked current Xilinx/XRT repository and it doesn't contains the fix for building on a Clang based kernel (it was added in [this PR of amd/xdna-driver](https://github.com/amd/xdna-driver/pull/866). In short: strip the `; cd ../..` suffix for all **dkms.conf.in** files in XRT repository.

As for amdxdna-dkms, it builds fine, but it doesn't work (even with my hand modified xrt fix for removing the missing macro/function call). I don't know why, maybe I've broken things although I doubt it, and honestly, I don't really want to waste time on those, since kernel 7.0 is coming and this would be useless IIUC.

@sofiageo : I'm sure if you check your pacman logs / dkms logs, you'll find you had DKMS build issues with both xrt and xrt-aws modules. It appears to work for you, because you don't need the xocl modules (for FastFlowLM at least), so the only things in xrt package you need (shared libraries and utility xrt-smi binary) are present in the package too. It's a bad idea to ignore this DKMS errors, since they'll reproduce for every update of linux you'll fetch and they'll amplify (you'll have a build failure for all version of kernels you have). 

And I'm not trying to build xrt, when you install xrt package, pacman **builds** xrt's XOCL modules via dkms. And since this fails and amdxdna-dkms package fails, I'm using amd/xdna-driver repository instead to build the amdxdna's Arch packages (that, in turns, builds xrt 2.23 packages) and install them. This works and it's the only thing that works without errors currently.

**Comment by sofiageo** [comment]
@X-Ryl669 As you also said, you don't need the xocl archive to run either Lemonade or FLM. So what is the issue here?

I get your frustration with the official Arch Linux procedures but there is nothing we can do about it, you can comment on the xrt gitlab but you will probably get the same answer [as I did](https://gitlab.archlinux.org/archlinux/packaging/packages/xrt/-/work_items/3), you should wait until it's merged.

I also don't think this issue is the proper place to vent, if you want to discuss it more feel free to join our discord.

**Comment by X-Ryl669** [comment]
> So what is the issue here?

Instructions don't work, results in a broken system (A broken DKMS module and a Chimera OS is a broken system, IMHO). Solution exists but isn't documented correctly. I've posted the solution above in my first reply for other users.

**Comment by superm1** [comment]
Once https://gitlab.archlinux.org/archlinux/packaging/packages/xrt/-/merge_requests/5 is merged it will fix your chief complaint.

**Comment by X-Ryl669** [comment]
Ok, thanks. TBH, I think the issue is also in xocl module too (and in fact all modules that are built with xrt). The fix is in this patch:
```diff
diff --git a/src/CMake/config/dkms-awsmgmt/dkms.conf.in b/src/CMake/config/dkms-awsmgmt/dkms.conf.in
index 508533a3b..4d71172ca 100644
--- a/src/CMake/config/dkms-awsmgmt/dkms.conf.in
+++ b/src/CMake/config/dkms-awsmgmt/dkms.conf.in
@@ -1,7 +1,7 @@
 PACKAGE_NAME="xrt-aws"
 PACKAGE_VERSION="@XRT_VERSION_STRING@"
-MAKE[0]="cd driver/aws; make KERNELDIR=${kernel_source_dir}; cd ../.."
-CLEAN="cd driver/aws; make clean KERNELDIR=${kernel_source_dir}; cd ../.."
+MAKE[0]="cd driver/aws; make KERNELDIR=${kernel_source_dir}"
+CLEAN="cd driver/aws; make clean KERNELDIR=${kernel_source_dir}"
 BUILT_MODULE_NAME[0]="awsmgmt"
 BUILT_MODULE_LOCATION[0]="driver/aws/mgmt"
 DEST_MODULE_LOCATION[0]="/kernel/extras"
diff --git a/src/CMake/config/dkms-xocl/dkms.conf.in b/src/CMake/config/dkms-xocl/dkms.conf.in
index 9e7c604b6..dc1b8407e 100644
--- a/src/CMake/config/dkms-xocl/dkms.conf.in
+++ b/src/CMake/config/dkms-xocl/dkms.conf.in
@@ -1,7 +1,7 @@
 PACKAGE_NAME="xrt"
 PACKAGE_VERSION="@XRT_VERSION_STRING@"
-MAKE[0]="cd driver/xocl; make KERNEL_SRC=${kernel_source_dir}; cd ../.."
-CLEAN="cd driver/xocl; make clean KERNEL_SRC=${kernel_source_dir}; cd ../.."
+MAKE[0]="cd driver/xocl; make KERNEL_SRC=${kernel_source_dir}"
+CLEAN="cd driver/xocl; make clean KERNEL_SRC=${kernel_source_dir}"
 BUILD_EXCLUSIVE_CONFIG="CONFIG_DRM"
 BUILT_MODULE_NAME[0]="xocl"
 BUILT_MODULE_LOCATION[0]="driver/xocl/userpf"
diff --git a/src/CMake/config/dkms-zocl/dkms.conf.in b/src/CMake/config/dkms-zocl/dkms.conf.in
index c79c23c20..c0266dd1e 100644
--- a/src/CMake/config/dkms-zocl/dkms.conf.in
+++ b/src/CMake/config/dkms-zocl/dkms.conf.in
@@ -1,7 +1,7 @@
 PACKAGE_NAME="xrt-zocl"
 PACKAGE_VERSION="@XRT_VERSION_STRING@"
-MAKE[0]="cd driver/zocl; make -j KERNEL_SRC=${kernel_source_dir}; cd ../.."
-CLEAN="cd driver/zocl; make clean KERNEL_SRC=${kernel_source_dir}; cd ../.."
+MAKE[0]="cd driver/zocl; make -j KERNEL_SRC=${kernel_source_dir}"
+CLEAN="cd driver/zocl; make clean KERNEL_SRC=${kernel_source_dir}"
 BUILT_MODULE_NAME[0]="zocl"
 BUILT_MODULE_LOCATION[0]="driver/zocl"
 DEST_MODULE_LOCATION[0]="/kernel/extras"
```

You've already applied the PR for 6.19 breakage with DRM_ERROR. 

BTW, why not using the latest XRT code in the Arch's PKGBUILD instead of piling up patches ?

**Comment by superm1** [comment]
For NPU support it's not needed

I don't see a problem with bumping to it as another approach to the issue through. If alveo support is rejected (or even as an another parallel stream) feel free to propose that as PR to xrt and xdna packaging.

**Comment by X-Ryl669** [comment]
I'm probably not clear. Current XRT package in ArchLinux install a DKMS source code for xrt module (and xrt-aws). In this xrt module, you've xocl (used by opencl implementation of NPU? I'm 100% guessing here, never used that). This xocl module (installed in `/usr/src/xrt-2.21.0` and `/usr/src/xrt-aws-2.21.0` contains two `dkms.conf` file that breaks DKMS and the system update because the `MAKE[0]` and `CLEAN` variable are wrong for any clang built kernel, typically used in CachyOS. 

There's nothing to do with Alveo here. The bare package is broken and even with the merge request #5 on the Arch's gitlab, it's still broken.

I've already proposed a PR fixing this exact issue with kashif in xdna driver repo and it was merged last november (although, the xdna driver doesn't build xrt's xocl as DKMS). 

I can propose a change to Xilinx/XRT repository but it won't appear in Arch linux anytime soon, since the current master is at 2.23 and Arch is packaging last November's 2.21 version.

**Comment by superm1** [comment]
We shouldn't need any of the dkms packages that are on xrt. We need amdxdna which doesn't come with that. It comes with the kernel.

**Comment by X-Ryl669** [comment]
I know. Yet, it's all or nothing. You need xrt because fastflowlm package depends on it. And if you install flm, you end up with a broken system. A better solution would be to split the xrt package in 2 (for example: xrt-libs and xrt-modules) and fix fastflowlm to use the former instead of xrt.
 

Please read again my first post, I've explained the steps for working: 
1. install fastflowlm, 
2. uninstall xrt (without uninstalling dependencies with pacman -Rdd xrt) 
3. install amdxdna from the repository (that'll build 3 packages: xrt-base, xrt-npu, amdxdna dkms, you'll need to install) since amdxdna-dkms package in AUR doesn't work - or wait until 7.0 is mainstream IIUC.

**Comment by superm1** [comment]
Did you actually test my PR?  Because I just did and I don't see a single DKMS package in it.

Here is a file listing captured with it.
```
less xrt-1:2.21.75-3-x86_64.pkg.tar.zst > listing.txt
```
[listing.txt](https://github.com/user-attachments/files/26095778/listing.txt)

**Comment by X-Ryl669** [comment]
No, I haven't. I've looked at the Modifications tab, and only found this that was related to something important:
```
     -D XRT_BASE=1
    -D XRT_ALVEO=0
    -D XRT_BUILD_NUMBER=$(awk --field-separator="." '{print $NF}' <<< "$pkgver")
```

My fault. I'll retry now that your change is merged in Arch. 

EDIT: It's working (no more DKMS stuff happening here).

**Comment by X-Ryl669** [comment]
But it still doesn't work for detecting NPU with amdxdna-dkms:
```
~/
❯ modinfo amdxdna
filename:       /lib/modules/6.19.8-1-cachyos/updates/dkms/amdxdna.ko.zst
import_ns:      DMA_BUF
firmware:       amdnpu/1502_00/npu.sbin
firmware:       amdnpu/17f0_10/npu.sbin
firmware:       amdnpu/17f0_11/npu.sbin
firmware:       amdnpu/17f0_20/npu.sbin
firmware:       amdnpu/1502_00/npu_7.sbin
firmware:       amdnpu/17f0_10/npu_7.sbin
firmware:       amdnpu/17f0_11/npu_7.sbin
license:        GPL
author:         XRT Team <runtimeca39d@amd.com>
description:    amdxdna driver
name:           amdxdna
depends:        gpu-sched
alias:          pci:v00001022d00001502sv*sd*bc*sc*i*
alias:          pci:v00001022d000017F0sv*sd*bc*sc*i*
srcversion:     45947F6FDD685405C5BDEC6
vermagic:       6.19.8-1-cachyos SMP preempt mod_unload
retpoline:      Y
sig_id:         PKCS#7
signer:         DKMS module signing key
sig_key:        2F:8C:41:8F:11:C3:75:53:D6:49:8F:74:95:78:B7:B8:F9:B5:33:E5
sig_hashalgo:   sha512
signature:      65:98:61:3F:A2:72:7C:5D:F7:DE:FE:55:F7:DE:29:48:62:49:2A:57:
                5B:BC:CF:92:9A:A8:5C:F3:0C:14:4E:89:CC:82:E6:8B:82:28:03:94:
                A8:46:94:60:50:42:3F:D7:87:25:61:7C:47:61:82:D2:9E:24:6A:30:
                67:70:2E:DC:42:6F:85:B5:57:24:75:44:09:B1:7A:09:E8:37:31:CB:
                63:00:73:3C:82:01:8F:9F:ED:42:78:AD:11:AA:2F:AC:0C:BE:44:A4:
                48:61:1E:13:3D:21:C5:F6:79:6C:3F:1B:CD:BD:5F:AA:4B:40:63:76:
                60:64:4B:69:C3:A0:A0:4B:BD:7E:03:F7:A3:05:B8:52:09:F3:E2:F4:
                CD:0B:CC:20:74:A4:62:EB:9C:9D:47:92:6E:9D:56:36:55:50:0C:DE:
                A8:18:D9:57:12:8B:4D:28:E3:3F:4E:37:1F:39:F7:21:C0:54:06:06:
                7D:69:44:EB:76:36:44:D8:54:86:04:FC:34:27:F5:94:CA:DB:DD:0B:
                34:71:82:FA:BE:03:7C:84:E6:3D:B2:E3:26:DD:36:EA:12:09:4B:FD:
                CF:C9:64:82:33:C5:6D:74:EB:34:A0:C6:45:7A:3B:F7:61:7B:79:6B:
                07:12:CB:E3:57:9A:30:3C:4F:0E:47:9A:37:51:50:2A
parm:           aie2_max_col:Maximum column could be used (uint)
parm:           force_cmdlist:Force use command list (Default true) (bool)

~/
❯ xrt-smi examine
System Configuration
  OS Name              : Linux
  Release              : 6.19.8-1-cachyos
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 31368 MB
  Distribution         : CachyOS
  GLIBC                : 2.43
  Model                : 83HY
  BIOS Vendor          : LENOVO
  BIOS Version         : R0CN16WW
  Processor            : AMD Ryzen AI 7 350 w/ Radeon 860M

XRT
  Version              : 2.21.75
  Branch               : makepkg
  Hash                 : 4eb1f4392a012b4e6eca759762389c612537f7c7
  Hash Date            : 2026-03-18 18:24:16

Device(s) Present
  0 devices found
```

So it's better because it doesn't break DKMS, but it does not work.

**Comment by superm1** [comment]
Do you have the xdna plugin installed? There is another package for it. They go together.

**Comment by X-Ryl669** [comment]
I thought I add it installed. Reinstalled it `sudo pacman -S xrt-plugin-amdxdna`. Rebooted and it works. The NPU firmware version is 1.1.2.64 while it used to be 255.something before. I guess it's normal.

**Comment by superm1** [comment]
Good.  255.XX.YY.ZZ means development (unstable) firmware version.

**Comment by superm1** [comment]
Here is a fix for the non-obvious dep:

https://gitlab.archlinux.org/archlinux/packaging/packages/fastflowlm/-/merge_requests/1

`pacman -S fastflowlm` should work from a clean system after that.

**Comment by ramkrishna2910** [comment]
Closing this as stale. Please open a new issue if problems persist.
